apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: bridge
  namespace: ${NAMESPACE}
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - ${BRIDGE_HOST}
      secretName: ${BRIDGE_TLS_SECRET_NAME}
  rules:
    - host: ${BRIDGE_HOST}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: bridge
                port:
                  number: 8081
