apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - pvc-graphrag.yaml
  - configmap.yaml
  - configmap-searxng.yaml
  - deployment-bridge.yaml
  - service-bridge.yaml
  - deployment-pipelines.yaml
  - service-pipelines.yaml
  - deployment-openwebui.yaml
  - service-openwebui.yaml
  - deployment-keycloak.yaml
  - service-keycloak.yaml
  - deployment-searxng.yaml
  - service-searxng.yaml
  - deployment-valkey.yaml
  - service-valkey.yaml
  - ingress-openwebui.yaml
  - ingress-keycloak.yaml
  - ingress-searxng.yaml
  - job-graphrag-index.yaml
